import { openai } from "./openai.js";
import { EventEmitter } from "events";

/**
 * Real-Time Website Builder
 * Generates websites with live progress updates and CSS styling
 * 
 * Features:
 * - Step-by-step generation with progress updates
 * - Live CSS styling preview
 * - Component-by-component building
 * - Real-time status broadcasts
 * - Visual progress tracking
 */

class RealtimeWebsiteBuilder extends EventEmitter {
  constructor() {
    super();
    this.currentBuild = null;
  }

  /**
   * Generate website with real-time updates
   */
  async generateWithProgress(requirements, projectId) {
    this.currentBuild = {
      projectId,
      status: "starting",
      progress: 0,
      currentStep: "Initializing",
      files: {},
      components: [],
    };

    try {
      // Step 1: Analyze requirements (10%)
      this.emitProgress(10, "Analyzing requirements...");
      await this.sleep(500);
      const analysis = await this.analyzeRequirements(requirements);

      // Step 2: Generate design system (20%)
      this.emitProgress(20, "Creating design system and CSS...");
      await this.sleep(500);
      const designSystem = await this.generateDesignSystem(requirements);
      this.currentBuild.files["app/globals.css"] = designSystem;

      // Step 3: Generate layout (35%)
      this.emitProgress(35, "Building layout structure...");
      await this.sleep(500);
      const layout = await this.generateLayout(requirements);
      this.currentBuild.files["app/layout.js"] = layout;

      // Step 4: Generate homepage (50%)
      this.emitProgress(50, "Creating homepage content...");
      await this.sleep(800);
      const homepage = await this.generateHomepage(requirements);
      this.currentBuild.files["app/page.js"] = homepage;

      // Step 5: Generate components (70%)
      this.emitProgress(70, "Building components...");
      await this.sleep(600);
      const components = await this.generateComponents(requirements);
      Object.assign(this.currentBuild.files, components);

      // Step 6: Generate package.json (85%)
      this.emitProgress(85, "Configuring project...");
      await this.sleep(400);
      this.currentBuild.files["package.json"] = this.generatePackageJson(requirements);

      // Step 7: Final touches (100%)
      this.emitProgress(100, "Website ready!");
      this.currentBuild.status = "completed";

      return {
        status: "success",
        files: this.currentBuild.files,
        components: this.currentBuild.components,
      };

    } catch (error) {
      this.emitProgress(0, `Error: ${error.message}`, "error");
      throw error;
    }
  }

  /**
   * Analyze requirements with AI
   */
  async analyzeRequirements(requirements) {
    const prompt = `Analyze these website requirements and return a JSON structure:
${JSON.stringify(requirements, null, 2)}

Return: {
  "theme": "color theme suggestion",
  "style": "design style (modern/minimal/bold)",
  "sections": ["list", "of", "sections"],
  "features": ["list", "of", "features"]
}`;

    const response = await openai.chat.completions.create({
      model: "openai/gpt-4",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
    });

    try {
      return JSON.parse(response.choices[0].message.content);
    } catch {
      return {
        theme: "blue",
        style: "modern",
        sections: ["hero", "features", "cta"],
        features: requirements.features || [],
      };
    }
  }

  /**
   * Generate comprehensive CSS design system
   */
  async generateDesignSystem(requirements) {
    const colors = requirements.brand?.colors || {
      primary: "#2563eb",
      secondary: "#8b5cf6",
      accent: "#f59e0b",
    };

    return `/* Design System - Generated by LeadForge AI */

:root {
  /* Colors */
  --primary: ${colors.primary || "#2563eb"};
  --primary-light: ${this.lightenColor(colors.primary || "#2563eb")};
  --primary-dark: ${this.darkenColor(colors.primary || "#2563eb")};
  
  --secondary: ${colors.secondary || "#8b5cf6"};
  --accent: ${colors.accent || "#f59e0b"};
  
  --text: #1a202c;
  --text-light: #4a5568;
  --text-lighter: #718096;
  
  --bg: #ffffff;
  --bg-secondary: #f7fafc;
  --bg-tertiary: #edf2f7;
  
  --border: #e2e8f0;
  --shadow: rgba(0, 0, 0, 0.1);
  
  /* Typography */
  --font-sans: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  --font-display: 'Inter', -apple-system, sans-serif;
  
  /* Spacing */
  --space-xs: 0.5rem;
  --space-sm: 1rem;
  --space-md: 1.5rem;
  --space-lg: 2rem;
  --space-xl: 3rem;
  --space-2xl: 4rem;
  
  /* Radius */
  --radius-sm: 0.375rem;
  --radius: 0.5rem;
  --radius-lg: 0.75rem;
  --radius-xl: 1rem;
  --radius-full: 9999px;
}

* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: var(--font-sans);
  color: var(--text);
  background: var(--bg);
  line-height: 1.6;
  -webkit-font-smoothing: antialiased;
}

/* Typography */
h1, h2, h3, h4, h5, h6 {
  font-family: var(--font-display);
  font-weight: 700;
  line-height: 1.2;
  margin-bottom: var(--space-md);
  color: var(--text);
}

h1 { font-size: 3rem; }
h2 { font-size: 2.25rem; }
h3 { font-size: 1.875rem; }
h4 { font-size: 1.5rem; }
h5 { font-size: 1.25rem; }
h6 { font-size: 1.125rem; }

p {
  margin-bottom: var(--space-md);
  color: var(--text-light);
}

/* Layout */
.container {
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 var(--space-md);
}

.section {
  padding: var(--space-2xl) 0;
}

/* Buttons */
.btn {
  display: inline-flex;
  align-items: center;
  gap: 0.5rem;
  padding: 0.75rem 1.5rem;
  border-radius: var(--radius-lg);
  font-weight: 600;
  font-size: 1rem;
  cursor: pointer;
  transition: all 0.2s;
  text-decoration: none;
  border: none;
}

.btn-primary {
  background: var(--primary);
  color: white;
}

.btn-primary:hover {
  background: var(--primary-dark);
  transform: translateY(-2px);
  box-shadow: 0 10px 20px var(--shadow);
}

.btn-secondary {
  background: var(--secondary);
  color: white;
}

.btn-outline {
  background: transparent;
  border: 2px solid var(--primary);
  color: var(--primary);
}

/* Cards */
.card {
  background: white;
  border-radius: var(--radius-lg);
  padding: var(--space-lg);
  box-shadow: 0 4px 6px var(--shadow);
  transition: transform 0.2s, box-shadow 0.2s;
}

.card:hover {
  transform: translateY(-4px);
  box-shadow: 0 12px 24px var(--shadow);
}

/* Grid */
.grid {
  display: grid;
  gap: var(--space-lg);
}

.grid-2 { grid-template-columns: repeat(2, 1fr); }
.grid-3 { grid-template-columns: repeat(3, 1fr); }
.grid-4 { grid-template-columns: repeat(4, 1fr); }

@media (max-width: 768px) {
  .grid-2, .grid-3, .grid-4 {
    grid-template-columns: 1fr;
  }
  
  h1 { font-size: 2rem; }
  h2 { font-size: 1.75rem; }
  
  .section {
    padding: var(--space-xl) 0;
  }
}

/* Animations */
@keyframes fadeIn {
  from { opacity: 0; transform: translateY(20px); }
  to { opacity: 1; transform: translateY(0); }
}

.animate-in {
  animation: fadeIn 0.6s ease-out;
}

/* Utilities */
.text-center { text-align: center; }
.text-primary { color: var(--primary); }
.bg-primary { background: var(--primary); }
.bg-secondary { background: var(--bg-secondary); }
.rounded { border-radius: var(--radius); }
.shadow { box-shadow: 0 4px 6px var(--shadow); }
`;
  }

  /**
   * Generate layout with navigation
   */
  async generateLayout(requirements) {
    const brandName = requirements.brand?.name || requirements.siteType || "My Site";
    
    return `import './globals.css'

export const metadata = {
  title: '${brandName}',
  description: 'Generated by LeadForge AI',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="nav">
          <div className="container" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '1.5rem' }}>
            <div style={{ fontSize: '1.5rem', fontWeight: 'bold', color: 'var(--primary)' }}>
              ${brandName}
            </div>
            <div style={{ display: 'flex', gap: '2rem' }}>
              <a href="#home" style={{ color: 'var(--text)', textDecoration: 'none' }}>Home</a>
              <a href="#features" style={{ color: 'var(--text)', textDecoration: 'none' }}>Features</a>
              <a href="#contact" style={{ color: 'var(--text)', textDecoration: 'none' }}>Contact</a>
            </div>
          </div>
        </nav>
        {children}
        <footer style={{ background: 'var(--bg-secondary)', padding: 'var(--space-xl)', textAlign: 'center', marginTop: 'var(--space-2xl)' }}>
          <p style={{ color: 'var(--text-light)' }}>© 2026 ${brandName}. All rights reserved.</p>
        </footer>
      </body>
    </html>
  )
}`;
  }

  /**
   * Generate homepage with sections
   */
  async generateHomepage(requirements) {
    const prompt = `Generate a modern homepage for a ${requirements.siteType} website.

Brand: ${requirements.brand?.name || "Brand"}
Tone: ${requirements.brand?.tone || "professional"}
Features: ${requirements.features?.join(", ") || "general"}

Create JSX with:
1. Hero section with headline and CTA
2. Features section (3 cards)
3. CTA section

Use modern design, className for styling. Return ONLY the JSX component code.`;

    const response = await openai.chat.completions.create({
      model: "openai/gpt-4",
      messages: [{ role: "user", content: prompt }],
      temperature: 0.7,
    });

    let content = response.choices[0].message.content.trim();
    
    // Remove markdown code fences if present
    content = content.replace(/```jsx?\n?/g, "").replace(/```\n?$/g, "");
    
    // Ensure it starts with export default
    if (!content.includes("export default")) {
      content = `export default function HomePage() {\n  return (\n${content}\n  )\n}`;
    }

    return content;
  }

  /**
   * Generate reusable components
   */
  async generateComponents(requirements) {
    const components = {};

    // Generate a feature card component
    components["components/FeatureCard.js"] = `export default function FeatureCard({ icon, title, description }) {
  return (
    <div className="card">
      <div style={{ fontSize: '2.5rem', marginBottom: 'var(--space-md)' }}>{icon}</div>
      <h3>{title}</h3>
      <p>{description}</p>
    </div>
  )
}`;

    // Generate a button component
    components["components/Button.js"] = `export default function Button({ children, variant = 'primary', onClick }) {
  return (
    <button className={\`btn btn-\${variant}\`} onClick={onClick}>
      {children}
    </button>
  )
}`;

    this.currentBuild.components = Object.keys(components);
    return components;
  }

  /**
   * Generate package.json
   */
  generatePackageJson(requirements) {
    const name = (requirements.brand?.name || requirements.siteType || "leadforge-site")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-");

    return JSON.stringify({
      name,
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "^14.2.0",
        react: "^18.3.0",
        "react-dom": "^18.3.0",
      },
    }, null, 2);
  }

  /**
   * Emit progress update
   */
  emitProgress(progress, message, status = "building") {
    this.currentBuild.progress = progress;
    this.currentBuild.currentStep = message;
    this.currentBuild.status = status;

    this.emit("progress", {
      projectId: this.currentBuild.projectId,
      progress,
      message,
      status,
      files: Object.keys(this.currentBuild.files),
    });
  }

  /**
   * Helper: Sleep
   */
  sleep(ms) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  /**
   * Helper: Lighten color
   */
  lightenColor(hex) {
    // Simple lightening - you can improve this
    return hex + "22"; // Add alpha for lighter version
  }

  /**
   * Helper: Darken color
   */
  darkenColor(hex) {
    // Simple darkening
    return hex.replace(/^#/, "#") + "dd";
  }
}

// Singleton
let builderInstance = null;

export function getRealtimeBuilder() {
  if (!builderInstance) {
    builderInstance = new RealtimeWebsiteBuilder();
  }
  return builderInstance;
}
