export const metadata = {
  title: "website",
  description: "Generated by LeadForge AI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
