import fs from "node:fs/promises";
import path from "node:path";
import { openai } from "../lib/openai.js";

/**
 * Generates a minimal Next.js (App Router) site from structured requirements.
 * Returns a map of { "relative/file/path.ext": "file contents" }.
 *
 * This intentionally generates a SMALL set of core files (landing page,
 * layout, one component per requested feature) rather than a full app in one
 * shot - large multi-file codegen is much more reliable when done file-by-file
 * with a tight prompt per file than as one giant completion.
 */
export async function generateSite(requirements) {
  const files = {};

  files["package.json"] = JSON.stringify(
    {
      name: slugify(requirements.brand?.name || requirements.siteType || "leadforge-site"),
      version: "0.1.0",
      private: true,
      scripts: { dev: "next dev", build: "next build", start: "next start" },
      dependencies: {
        next: "^14.2.0",
        react: "^18.3.0",
        "react-dom": "^18.3.0",
        ...(requirements.integrations?.includes("Supabase")
          ? { "@supabase/supabase-js": "^2.45.0" }
          : {}),
      },
    },
    null,
    2
  );

  files["app/layout.js"] = `export const metadata = {
  title: "${requirements.brand?.name || requirements.siteType}",
  description: "Generated by LeadForge AI",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`;

  // Ask the model for the homepage content only - keeps generation focused
  // and cheap, and avoids the model inventing extra pages/routes that don't
  // exist in the requirements.
  const prompt = `Generate the JSX body content (no imports, no component wrapper) for a homepage of a "${requirements.siteType}" site.
Brand tone: ${requirements.brand?.tone || "clean and professional"}.
Features to reflect in the copy/sections: ${requirements.features.join(", ") || "none specified"}.
Return ONLY valid JSX for inside a <main> element - no markdown fences, no explanation.`;

  const completion = await openai.chat.completions.create({
    model: "gpt-4o-mini",
    messages: [{ role: "user", content: prompt }],
    temperature: 0.5,
  });

  const bodyJsx = completion.choices[0]?.message?.content?.trim() ?? "<h1>Coming soon</h1>";

  files["app/page.js"] = `export default function HomePage() {
  return (
    <main>
      ${bodyJsx}
    </main>
  );
}
`;

  if (requirements.integrations?.includes("Supabase")) {
    files["lib/supabaseClient.js"] = `import { createClient } from "@supabase/supabase-js";

export const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
);
`;
  }

  return files;
}

/** Writes generated files to disk under a project-specific directory. */
export async function writeProjectToDisk(projectId, files) {
  const root = path.join(process.cwd(), "generated-sites", projectId);
  await fs.mkdir(root, { recursive: true });
  for (const [relPath, content] of Object.entries(files)) {
    const fullPath = path.join(root, relPath);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, content, "utf-8");
  }
  return root;
}

/**
 * Deploys a generated site directory to Vercel using the Vercel REST API.
 * Requires VERCEL_TOKEN in env. This posts file contents directly rather
 * than shelling out to the `vercel` CLI, so it works in serverless/CI contexts.
 * https://vercel.com/docs/rest-api/endpoints/deployments
 */
export async function deployToVercel(projectName, files) {
  if (!process.env.VERCEL_TOKEN) {
    throw new Error("VERCEL_TOKEN is not set - cannot deploy. Add it to backend/.env");
  }

  const deploymentFiles = Object.entries(files).map(([file, data]) => ({
    file,
    data,
  }));

  const res = await fetch(
    `https://api.vercel.com/v13/deployments${
      process.env.VERCEL_TEAM_ID ? `?teamId=${process.env.VERCEL_TEAM_ID}` : ""
    }`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: slugify(projectName),
        files: deploymentFiles,
        target: "production",
        projectSettings: { framework: "nextjs" },
      }),
    }
  );

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Vercel deploy failed (${res.status}): ${errText}`);
  }

  const data = await res.json();
  return { url: `https://${data.url}`, deploymentId: data.id };
}

function slugify(str) {
  return (str || "leadforge-site")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
