import fs from "node:fs/promises";
import path from "node:path";
import { openai } from "../lib/openai.js";

/**
 * Generates a modern Next.js (App Router) site from structured requirements.
 * Uses the latest versions: Next.js 15, React 19, TypeScript, Tailwind CSS
 * Returns a map of { "relative/file/path.ext": "file contents" }.
 */
export async function generateSite(requirements) {
  const files = {};

  // Latest versions as of 2026
  files["package.json"] = JSON.stringify(
    {
      name: slugify(requirements.brand?.name || requirements.siteType || "leadforge-site"),
      version: "0.1.0",
      private: true,
      scripts: { 
        dev: "next dev --turbo",  // Turbopack for faster dev
        build: "next build", 
        start: "next start",
        lint: "next lint"
      },
      dependencies: {
        next: "^15.0.0",           // Latest Next.js 15
        react: "^19.0.0",          // Latest React 19
        "react-dom": "^19.0.0",    // React 19 DOM
        ...(requirements.integrations?.includes("Supabase")
          ? { "@supabase/supabase-js": "^2.45.0" }
          : {}),
      },
      devDependencies: {
        "@types/node": "^20.0.0",
        "@types/react": "^19.0.0",
        "@types/react-dom": "^19.0.0",
        typescript: "^5.3.0",
        tailwindcss: "^3.4.0",
        postcss: "^8.4.0",
        autoprefixer: "^10.4.0",
        eslint: "^8.0.0",
        "eslint-config-next": "^15.0.0"
      },
    },
    null,
    2
  );

  // TypeScript configuration
  files["tsconfig.json"] = JSON.stringify(
    {
      compilerOptions: {
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        esModuleInterop: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "preserve",
        incremental: true,
        plugins: [{ name: "next" }],
        paths: { "@/*": ["./*"] }
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
      exclude: ["node_modules"]
    },
    null,
    2
  );

  // Tailwind CSS configuration
  files["tailwind.config.ts"] = `import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
      },
    },
  },
  plugins: [],
};
export default config;
`;

  // PostCSS configuration
  files["postcss.config.js"] = `module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
`;

  // Root layout with TypeScript and Tailwind
  files["app/layout.tsx"] = `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "${requirements.brand?.name || requirements.siteType}",
  description: "Generated by LeadForge AI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
`;

  // Global CSS with Tailwind
  files["app/globals.css"] = `@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --background: #ffffff;
  --foreground: #171717;
}

@media (prefers-color-scheme: dark) {
  :root {
    --background: #0a0a0a;
    --foreground: #ededed;
  }
}

body {
  color: var(--foreground);
  background: var(--background);
  font-family: Arial, Helvetica, sans-serif;
}

@layer utilities {
  .text-balance {
    text-wrap: balance;
  }
}
`;

  // Ask the model for modern React 19 + TypeScript homepage
  const prompt = `Generate modern React 19 + TypeScript JSX for a "${requirements.siteType}" homepage.
Brand tone: ${requirements.brand?.tone || "clean and professional"}.
Features: ${requirements.features.join(", ") || "none specified"}.

Requirements:
- Use React 19 features (use client/server components appropriately)
- Use TypeScript with proper types
- Use Tailwind CSS classes for styling
- Modern, responsive design
- Semantic HTML
- Return ONLY the component code (imports + export default component)
- No markdown fences, no explanation`;

  const completion = await openai.chat.completions.create({
    model: "gpt-4o",  // Use latest model for better code generation
    messages: [{ role: "user", content: prompt }],
    temperature: 0.5,
  });

  const componentCode = completion.choices[0]?.message?.content?.trim() ?? 
    `export default function HomePage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Coming Soon</h1>
      <p className="mt-4 text-lg text-gray-600">
        ${requirements.brand?.name || "Your site"} is under construction
      </p>
    </main>
  );
}`;

  files["app/page.tsx"] = componentCode;

  // Add Supabase integration if requested
  if (requirements.integrations?.includes("Supabase")) {
    files["lib/supabase.ts"] = `import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!;

export const supabase = createClient(supabaseUrl, supabaseAnonKey);
`;

    files[".env.local.example"] = `NEXT_PUBLIC_SUPABASE_URL=your-project-url
NEXT_PUBLIC_SUPABASE_ANON_KEY=your-anon-key
`;
  }

  // README with latest tech stack
  files["README.md"] = `# ${requirements.brand?.name || requirements.siteType}

Generated by LeadForge AI

## Tech Stack

- **Next.js 15** - React framework with App Router
- **React 19** - Latest React with Server Components
- **TypeScript** - Type-safe development
- **Tailwind CSS** - Utility-first styling
- **Turbopack** - Fast bundler (dev mode)

## Getting Started

\`\`\`bash
# Install dependencies
npm install

# Run development server (with Turbopack)
npm run dev

# Build for production
npm run build

# Start production server
npm start
\`\`\`

## Features

${requirements.features.map(f => `- ${f}`).join('\n')}

## Generated

This site was generated automatically based on requirements.
`;

  // .gitignore
  files[".gitignore"] = `# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
`;

  return files;
}

/** Writes generated files to disk under a project-specific directory. */
export async function writeProjectToDisk(projectId, files) {
  const root = path.join(process.cwd(), "generated-sites", projectId);
  await fs.mkdir(root, { recursive: true });
  for (const [relPath, content] of Object.entries(files)) {
    const fullPath = path.join(root, relPath);
    await fs.mkdir(path.dirname(fullPath), { recursive: true });
    await fs.writeFile(fullPath, content, "utf-8");
  }
  return root;
}

/**
 * Deploys a generated site directory to Vercel using the Vercel REST API.
 * Requires VERCEL_TOKEN in env. This posts file contents directly rather
 * than shelling out to the `vercel` CLI, so it works in serverless/CI contexts.
 * https://vercel.com/docs/rest-api/endpoints/deployments
 */
export async function deployToVercel(projectName, files) {
  if (!process.env.VERCEL_TOKEN) {
    throw new Error("VERCEL_TOKEN is not set - cannot deploy. Add it to backend/.env");
  }

  const deploymentFiles = Object.entries(files).map(([file, data]) => ({
    file,
    data,
  }));

  const res = await fetch(
    `https://api.vercel.com/v13/deployments${
      process.env.VERCEL_TEAM_ID ? `?teamId=${process.env.VERCEL_TEAM_ID}` : ""
    }`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${process.env.VERCEL_TOKEN}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: slugify(projectName),
        files: deploymentFiles,
        target: "production",
        projectSettings: { framework: "nextjs" },
      }),
    }
  );

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`Vercel deploy failed (${res.status}): ${errText}`);
  }

  const data = await res.json();
  return { url: `https://${data.url}`, deploymentId: data.id };
}

function slugify(str) {
  return (str || "leadforge-site")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/(^-|-$)/g, "");
}
